# Generated by Django 3.1.7 on 2021-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=250)),
                ('license_plate', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('km_age', models.IntegerField()),
                ('construction_date', models.SmallIntegerField()),
                ('vehicle_type', models.CharField(max_length=100)),
                ('gear_type', models.CharField(max_length=50)),
            ],
        ),
    ]
