# Generated by Django 3.1.7 on 2021-04-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
