# Generated by Django 3.1.7 on 2021-04-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarManagement', '0004_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
