# Generated by Django 3.1.7 on 2021-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarManagement', '0005_auto_20210428_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='gear_type',
        ),
        migrations.AddField(
            model_name='car',
            name='is_automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('LIMOSINE', 'Limosine'), ('COMBI', 'Combi'), ('KLEINWAGEN', 'Kleinwagen')], default='SUV', max_length=100),
        ),
    ]
