# Generated by Django 3.1.7 on 2021-05-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarManagement', '0006_auto_20210428_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='reserved',
        ),
    ]
