# Generated by Django 3.1.7 on 2021-04-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerManagement', '0001_initial'),
        ('CarManagement', '0005_auto_20210428_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CarManagement.car')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CustomerManagement.customer')),
            ],
        ),
    ]
