# Generated by Django 3.1.7 on 2021-05-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sec_name',
            new_name='last_name',
        ),
    ]
