# Generated by Django 3.1.7 on 2021-05-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerManagement', '0002_auto_20210501_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='residence_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='post_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
